### ISSUE TITLE
CS1 Task 4: create UC 1011: "Log given medication"

### ISSUE THREAD

**Issue by raeffu** [raeffu/ch.bfh.bti7081.s2015.Blue#12]
Fill out use case form for "Log given medication" use case

Due date 20.03.2015

**Comment by klu1** [comment]
I'm not sure why I'm in this GitHub project but I don't think I'm supposed
to be. Please remove. Thanks

**Comment by raeffu** [comment]
@klu1 We accedently added you as contributor, but removed you. I think you're getting notifications because you watch our repository. You have to click unwatch, we cannot do that for you. Please check if this works!

Sorry and regards,
Raphael
